In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('/Users/jrenoj/Desktop/crime-dashboard/data/raw/export.csv')
pd.set_option('display.max_columns', None)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,2021 Apr 11 12:00:00 AM,2020 Nov 07 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,0377,31,M,H,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,2020 Oct 21 12:00:00 AM,2020 Oct 18 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0416 0334 2004 1822 1414 0305 0319 0400,32,M,H,102.0,SIDEWALK,200.0,KNIFE WITH BLADE 6INCHES OR LESS,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,2024 Dec 10 12:00:00 AM,2020 Oct 30 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,0377,30,M,W,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,2020 Dec 24 12:00:00 AM,2020 Dec 24 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,0344,47,F,A,101.0,STREET,NaN,NaN,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020 Oct 03 12:00:00 AM,2020 Sep 29 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1300 0344 1606 2032,63,M,H,103.0,ALLEY,NaN,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350

In [29]:
new = df[["DR_NO", "DATE OCC", "TIME OCC", "AREA NAME", "Crm Cd Desc", "Vict Age", "Vict Sex", "Vict Descent", "LAT", "LON"]]
new.head()

,DR_NO,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,LAT,LON
0,211507896,2020 Nov 07 12:00:00 AM,845,N Hollywood,THEFT OF IDENTITY,31,M,H,34.2124,-118.4092
1,201516622,2020 Oct 18 12:00:00 AM,1845,N Hollywood,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",32,M,H,34.1993,-118.4203
2,240913563,2020 Oct 30 12:00:00 AM,1240,Van Nuys,THEFT OF IDENTITY,30,M,W,34.1847,-118.4509
3,210704711,2020 Dec 24 12:00:00 AM,1310,Wilshire,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,47,F,A,34.0339,-118.3747
4,201418201,2020 Sep 29 12:00:00 AM,1830,Pacific,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),63,M,H,33.9813,-118.4350

In [ ]:
new["Year"] = pd.to_datetime(new["DATE OCC"]).dt.year
new["Month"] = pd.to_datetime(new["DATE OCC"]).dt.month_name()
new["Day"] = pd.to_datetime(new["DATE OCC"]).dt.day_name()
new["Time"] = (
    pd.to_datetime(new["TIME OCC"].astype(str).str.zfill(4), format="%H%M")
    .dt.hour.astype(str)
    + ":00"
)

/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  new["Year"] = pd.to_datetime(new["DATE OCC"]).dt.year
/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new["Year"] = pd.to_datetime(new["DATE OCC"]).dt.year
/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  new["Month"] = pd.to_datetime(new["DATE OCC"]).dt.month_name()
/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new["Month"] = pd.to_datetime(new["DATE OCC"]).dt.month_name()
/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  new["Day"] = pd.to_datetime(new["DATE OCC"]).dt.day_name()
/var/folders/zl/5qwj97qj4y5d7tj4vl4r46d80000gn/T/ipykernel_8848/1068638057.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new["Day"] = pd.to_datetime(new["DATE OCC"]).dt.day_name()

ValueError: time data "1" doesn't match format "%H%M", at position 10. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.